# Generated by Django 5.1.2 on 2024-11-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artists/avatars/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='EnsembleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория ансамбля',
                'verbose_name_plural': 'Категории ансамблей',
            },
        ),
        migrations.CreateModel(
            name='Family_of_instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Тип инструмента')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Тип инструмента (русский)')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Family of instruments',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Title',
            },
        ),
        migrations.CreateModel(
            name='EnsembleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа ансамбля')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ensemble_types', to='Score.ensemblecategory')),
            ],
            options={
                'verbose_name': 'Тип ансамбля',
                'verbose_name_plural': 'Типы ансамблей',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Инструмент')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Инструмент (русский)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instruments/avatars/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='Score.family_of_instruments', verbose_name='Тип инструмента')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_title', models.CharField(blank=True, max_length=100, verbose_name='Название обложки')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FileField(upload_to='scores/')),
                ('envelope', models.FileField(blank=True, upload_to='envelope/')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('part_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество партий')),
                ('page_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество страниц')),
                ('key', models.CharField(blank=True, max_length=100, verbose_name='Тональность')),
                ('measures', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Количество тактов')),
                ('file_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Хэш файла')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Score.artist', verbose_name='Исполнитель')),
                ('ensemble_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Score.ensembletype', verbose_name='Тип ансамбля')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ScoreInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Score.instrument')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Score.score')),
            ],
            options={
                'verbose_name': 'Инструмент в партитуре',
                'verbose_name_plural': 'Инструменты в партитурах',
                'unique_together': {('score', 'instrument')},
            },
        ),
        migrations.AddField(
            model_name='score',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='scores', through='Score.ScoreInstrument', to='Score.instrument'),
        ),
        migrations.AddField(
            model_name='score',
            name='title',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Score.title', verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['publication_date'], name='Score_score_publica_14a9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['slug'], name='Score_score_slug_e3d60e_idx'),
        ),
    ]
